project:
  type: website
  output-dir: _site

pagetitle: "surveydown USRSE"
title: "`surveydown`<br><span style='font-size: 0.7em;'>An open-source platform for programmable,<br>markdown-based surveys</span>"
author: "<br>**Pingfan Hu**<br>George Washington University<br><br>USRSE'25"

format:
  touhou-revealjs:
    smaller: false
    css: styles/slides.css
    include-after-body:
      - styles/bubble-align.html
    slide-number: true
    embed-resources: false
    auto-stretch: false
    footer: "<a href='https://pingfan.org'>Pingfan Hu</a> - <a href='https://us-rse.org/usrse25/'>USRSE'25</a>"
    preview-links: auto
    link-external-newwindow: true
    link-external-icon: false
    center-title-slide: true
    code-block-height: 650px
    title-slide-attributes:
      class: custom-title-slide
      style: "text-align:left; background-image: url(figs/logo-surveydown.png);"

execute:
  warning: false
  echo: false
